### ISSUE TITLE
`pip install tarman` failed

### ISSUE THREAD

**Issue by c02y** [matejc/tarman#25]
```
>> pip --version
pip 20.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)
>> pip install tarman
Defaulting to user installation because normal site-packages is not writeable
Collecting tarman
  Using cached tarman-0.1.3.zip (27 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qcgnj49j/tarman_c88cdebb54c94eddb066568646a059b9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qcgnj49j/tarman_c88cdebb54c94eddb066568646a059b9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dpkv2hrv
         cwd: /tmp/pip-install-qcgnj49j/tarman_c88cdebb54c94eddb066568646a059b9/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qcgnj49j/tarman_c88cdebb54c94eddb066568646a059b9/setup.py", line 29, in <module>
        constants = import_path(
      File "/tmp/pip-install-qcgnj49j/tarman_c88cdebb54c94eddb066568646a059b9/setup.py", line 20, in import_path
        reload(module)  # Might be out of date
    NameError: name 'reload' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
>> uname -a
Linux chz 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
```

**Comment by mharig** [comment]
Same here, end of 2022. This project is dead.
